//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthWindVisualizer.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Linq;

    public partial class Orders : INotifyPropertyChanged
    {
        public Orders()
        {
            this.Order_Details = new HashSet<Order_Details>();
        }

        public event PropertyChangedEventHandler PropertyChanged;

        private void NotifyPropertyChanged(String info)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(info));
            }
        }

        private int _OrderID { get; set; }
        private string _CustomerID { get; set; }
        private Nullable<int> _EmployeeID { get; set; }
        private Nullable<System.DateTime> _OrderDate { get; set; }
        private Nullable<System.DateTime> _RequiredDate { get; set; }
        private Nullable<System.DateTime> _ShippedDate { get; set; }
        private Nullable<int> _ShipVia { get; set; }
        private Nullable<decimal> _Freight { get; set; }
        private string _ShipName { get; set; }
        private string _ShipAddress { get; set; }
        private string _ShipCity { get; set; }
        public string _ShipRegion { get; set; }
        private string _ShipPostalCode { get; set; }
        private string _ShipCountry { get; set; }
        private  Customers _Customers { get; set; }
        private  Employees _Employees { get; set; }
        private  ICollection<Order_Details> _Order_Details { get; set; }

        public int OrderID
        {
            get
            {
                return _OrderID;
            }
            set
            {
                _OrderID = value;
                NotifyPropertyChanged("OrderID");
            }
        }
        public string CustomerID
        {
            get
            {
                return _CustomerID;
            }
            set
            {
                _CustomerID = value;
                NotifyPropertyChanged("CustomerID");
            }
        }
        public Nullable<int> EmployeeID
        {
            get
            {
                return _EmployeeID;
            }
            set
            {
                _EmployeeID = value;
                NotifyPropertyChanged("EmployeeID");
            }
        }
        public Nullable<System.DateTime> OrderDate
        {
            get
            {
                return _OrderDate;
            }
            set
            {
                _OrderDate = value;
                NotifyPropertyChanged("OrderDate");
            }
        }
        public Nullable<System.DateTime> RequiredDate
        {
            get
            {
                return _RequiredDate;
            }
            set
            {
                _RequiredDate = value;
                NotifyPropertyChanged("RequiredDate");
            }
        }
        public Nullable<System.DateTime> ShippedDate
        {
            get
            {
                return _ShippedDate;
            }
            set
            {
                _ShippedDate = value;
                NotifyPropertyChanged("ShippedDate");
            }
        }
        public Nullable<int> ShipVia
        {
            get
            {
                return _ShipVia;
            }
            set
            {
                _ShipVia = value;
                NotifyPropertyChanged("ShipVia");
            }
        }
        public Nullable<decimal> Freight
        {
            get
            {
                return _Freight;
            }
            set
            {
                _Freight = value;
                NotifyPropertyChanged("Freight");
            }
        }
        public string ShipName
        {
            get
            {
                return _ShipName;
            }
            set
            {
                _ShipName = value;
                NotifyPropertyChanged("ShipName");
            }
        }
        public string ShipAddress
        {
            get
            {
                return _ShipAddress;
            }
            set
            {
                _ShipAddress = value;
                NotifyPropertyChanged("ShipAddress");
            }
        }
        public string ShipCity
        {
            get
            {
                return _ShipCity;
            }
            set
            {
                _ShipCity = value;
                NotifyPropertyChanged("ShipCity");
            }
        }
        public string ShipRegion
        {
            get
            {
                return _ShipRegion;
            }
            set
            {
                _ShipRegion = value;
                NotifyPropertyChanged("ShipRegion");
            }
        }
        public string ShipPostalCode
        {
            get
            {
                return _ShipPostalCode;
            }
            set
            {
                _ShipPostalCode = value;
                NotifyPropertyChanged("ShipPostalCode");
            }
        }
        public string ShipCountry
        {
            get
            {
                return _ShipCountry;
            }
            set
            {
                _ShipCountry = value;
                NotifyPropertyChanged("ShipCountry");
            }
        }
        public virtual Customers Customers
        {
            get
            {
                return _Customers;
            }
            set
            {
                _Customers = value;
                NotifyPropertyChanged("Customers");
            }
        }
        public virtual Employees Employees
        {
            get
            {
                return _Employees;
            }
            set
            {
                _Employees = value;
                NotifyPropertyChanged("Employees");
            }
        }
        public virtual ICollection<Order_Details> Order_Details
        {
            get
            {
                return _Order_Details;
            }
            set
            {
                _Order_Details = value;
                NotifyPropertyChanged("Order_Details");
            }
        }
        public double TotalPrice
        {
            get { return Order_Details.Sum(x => Convert.ToDouble(x.Quantity * x.UnitPrice) - Convert.ToDouble(x.Discount)); }
        }
    }
}
