//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment40_PartIII.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.IO;
    public partial class NORTHWNDEntities1 : DbContext
    {
        public NORTHWNDEntities1()
            : base(@"Data Source=(LocalDB)\v11.0;AttachDbFilename="+(new FileInfo(System.Reflection.Assembly.GetEntryAssembly().Location)).Directory+@"\NORTHWND.MDF;Integrated Security=True;Connect Timeout=30;MultipleActiveResultSets=True;App=EntityFramework")
        {
        }
    
        public DbSet<Categories> Categories { get; set; }
        public DbSet<Order_Details> Order_Details { get; set; }
        public DbSet<Orders> Orders { get; set; }
        public DbSet<Products> Products { get; set; }
    }
}
