//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment40_1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Details
    {
        public Order_Details(Orders order, Products product, decimal unitPrice, short quantity, float discount)
        {
            this.OrderID = order.OrderID;
            this.ProductID = product.ProductID;
            this.UnitPrice = unitPrice;
            this.Quantity = quantity;
            this.Discount = discount;
            this.Orders = order;
            this.Products = product;
        }
        public int OrderID { get; set; }
        public int ProductID { get; set; }
        public decimal UnitPrice { get; set; }
        public short Quantity { get; set; }
        public float Discount { get; set; }    
        public virtual Orders Orders { get; set; }
        public virtual Products Products { get; set; }
    }
}
