//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment40_PartIII.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Assignment40_PartIII.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CategoryID;CategoryName;Description
        ///1;Beverages;Soft drinks, coffees, teas, beers, and ales
        ///2;Condiments;Sweet and savory sauces, relishes, spreads, and seasonings
        ///3;Confections;Desserts, candies, and sweet breads
        ///4;Dairy Products;Cheeses
        ///5;Grains/Cereals;Breads, crackers, pasta, and cereal
        ///6;Meat/Poultry;Prepared meats
        ///7;Produce;Dried fruit and bean curd
        ///8;Seafood;Seaweed and fish
        ///.
        /// </summary>
        internal static string categories {
            get {
                return ResourceManager.GetString("categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderID;ProductID;UnitPrice;Quantity;Discount
        ///10248;11;14;12;0
        ///10248;42;9.8;10;0
        ///10248;72;34.8;5;0
        ///10249;14;18.6;9;0
        ///10249;51;42.4;40;0
        ///10250;41;7.7;10;0
        ///10250;51;42.4;35;0.15000001
        ///10250;65;16.8;15;0.15000001
        ///10251;22;16.8;6;5.0000001E-2
        ///10251;57;15.6;15;5.0000001E-2
        ///10251;65;16.8;20;0
        ///10252;20;64.8;40;5.0000001E-2
        ///10252;33;2;25;5.0000001E-2
        ///10252;60;27.2;40;0
        ///10253;31;10;20;0
        ///10253;39;14.4;42;0
        ///10253;49;16;40;0
        ///10254;24;3.6;15;0.15000001
        ///10254;55;19.2;21;0.15000001
        ///10254;74;8;21;0
        ///102 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string order_details {
            get {
                return ResourceManager.GetString("order_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderID;CustomerID;EmployeeID;OrderDate;RequiredDate;ShippedDate;ShipVia;Freight;ShipName;ShipAddress;ShipCity;ShipRegion;ShipPostalCode;ShipCountry
        ///10248;VINET;5;1996-07-04 00:00:00;1996-08-01 00:00:00;1996-07-16 00:00:00;3;32.38;Vins et alcools Chevalier;59 rue de l&apos;Abbaye;Reims;;51100;France
        ///10249;TOMSP;6;1996-07-05 00:00:00;1996-08-16 00:00:00;1996-07-10 00:00:00;1;11.61;Toms Spezialit„ten;Luisenstr. 48;Mnster;;44087;Germany
        ///10250;HANAR;4;1996-07-08 00:00:00;1996-08-05 00:00:00;1996-07-12 00:00:00;2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string orders {
            get {
                return ResourceManager.GetString("orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductID;ProductName;SupplierID;CategoryID;QuantityPerUnit;UnitPrice;UnitsInStock;UnitsOnOrder;ReorderLevel;Discontinued
        ///1;Chai;1;1;10 boxes x 20 bags;18;39;0;10;0
        ///2;Chang;1;1;24 - 12 oz bottles;19;17;40;25;0
        ///3;Aniseed Syrup;1;2;12 - 550 ml bottles;10;13;70;25;0
        ///4;Chef Anton&apos;s Cajun Seasoning;2;2;48 - 6 oz jars;22;53;0;0;0
        ///5;Chef Anton&apos;s Gumbo Mix;2;2;36 boxes;21.35;0;0;0;-1
        ///6;Grandma&apos;s Boysenberry Spread;3;2;12 - 8 oz jars;25;120;0;25;0
        ///7;Uncle Bob&apos;s Organic Dried Pears;3;7;12 - 1 lb pkgs.;30;15;0; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string products {
            get {
                return ResourceManager.GetString("products", resourceCulture);
            }
        }
    }
}
